### ISSUE TITLE
this is not secure

### ISSUE THREAD

**Issue by dominictarr** [mikeal/resilient-swarm#1]
at most, it would be fair to call what you are doing here as _obsfucation_

first problem is here:

https://github.com/mikeal/resilient-swarm/blob/master/index.js#L24

This uses the same key for each encryption, between any two peers.
Since aes is a block cipher, the output of the previous block becomes part of the key of the next block,
so if have a ciphertext/plaintext pair from the a previous session you can xor that and get the key stream - if the plaintext in the first text is different (likely) then the second block will be different, but the first block will be decryptable.

since this is a group chat thing, you might send a message session where myself and alice both receive the same initial messages. If I can observe the ciphertext between you and alice, I can compare it with the ciphertext you sent me, plus the plaintext, and then I'll be able to decrypt the start of future sessions between you and alice.

That isn't even getting taking into key authentication or forward security.

if you are gonna make a claim about "cryptographic security" you really need to do your homework and show your working. I.e. document what security properties you are claiming and why.

**Comment by mikeal** [comment]
that link doesn't work anymore because I just did a big re-write so I'm not sure which specific part you were referring to.

at the moment, this isn't doing any additional cypher streams on top of what webrtc already does for encryption.  the only additional thing that is encrypted are the signals that get relayed between peers so that the relaying peer can't read or modify the signal.

_eventually_ I'll also be using a cypher stream to encrypt the data channel between relay peers but that is on hold until i figure out the proper metrics for deciding when to relay through peers rather than directly connect.

**Comment by mikeal** [comment]
I pulled up an old tag and I think your comment is in relation to the cypherStream function.

That function is actually unused, it's there from a prior experiment, and the secret passed to the function was computed previous to creating the stream from the public keys of both peers so, no, it's not the same secret for every peer :)

**Comment by dominictarr** [comment]
sorry, I meant it was the same secret for each pair of peers. (so, between you and I, the same secret is used, but between you and Bob, another secret is used, but it's the same each time)

**Comment by dominictarr** [comment]
ps, great rename!

**Comment by mikeal** [comment]
> but it's the same each time

So, every time a client joins the swarm they use a new keypair, so is this still a concern? The keypair being used during this _session_ is temporary. It only ever lives in memory, we don't even write it to storage or expose it.

**Comment by dominictarr** [comment]
That is an certainly an improvement, but given that you close the lid on your laptop and it goes into suspend and most people have like 50 open tabs, that memory may persist quite a long time.

The way that a cryptographer approaches system design is they imagine powers for the attacker to have, and then try to prevent those powers being useful to them. Those powers might be actually quite unlikely to have in practice, or would require great dedication to achive (say, observing all cyphertexts in the network) But using this approach actually simplifies the design process, or rather, simplifies the auditing process.
For an ordinary module, we want to know it's correct, and the way we do that is to test it. Sometimes that means actually changing the way we are coding it to make it easier to test. The security version of that, is designing it in a way to make it easier to audit.

Ideally, all the security can be in crypto, then you can verify the design is safe only looking at the protocol spec (or even just an abstract description of it). Then you just have to check whether the implementation is a straightforward implementation of the specification. The new school of crypto libraries (nacl/sodium) follow this approach - the old school (openssl) don't. My joke is that if it's name is a three letter acronym, then it has a weird bug or edgecase that is a security footgun if you don't know about it. but it's actually true of AES, SHA, RSA (in openssl) and the primitives in NACL are carefully designed to avoid it (although it still has SHA)

When you have a edge case (like "dont keep a key active too long") then you have to analyze the way the application uses it to decide whether it's secure. That is much harder, and gives the attacker a lot of wiggle room. maybe there are other situations where the assumption doesn't apply?

Like, on servers or IoT, a peer may stay connected to a swarm for a much longer time, on phones prehaps it's more reasonable.

Anyway, my point is, if you are gonna say it's secure, you should take security seriously, and build a strong design, not just system where the security is only held together by coincidences in the implementation.
