### ISSUE TITLE
Question : What is the network topology used in kill-beez ?

### ISSUE THREAD

**Issue by karuppiah7890** [mikeal/resilient-swarm#4]
What topology is used in killa-beez ? Is it mesh ?

**Comment by sesam** [comment]
It says something about registering, so I guessed there needs to be a "SIP server" component to register with.
Reading more, it seems to use https://github.com/mikeal/signal-exchange and private/public keys are used to join a channel. So to participate in anything you would need the channel key? And all channel participants would presumably try to connect with all other participants? Flooding? Try to forward to registered, then forget the message?
Ping @mikeal

**Comment by mikeal** [comment]
killa-beez uses WebRTC which can establish connections too peers without a
SIP server. WebRTC has its own protocol but uses STUN/TURN for describing a
peer and getting through a NAT.

Right now, every peer in the swarm has a connection to every other peer.
There are plans to make this topology smarter, with "super nodes," but the
problem with doing that right now is that no browser yet supports a
standard that will proxy media (video and audio) so the only thing you
would be able to move around with a smarter topology is the raw data
channel.
